// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:92289ce1-158a-48ce-b8a9-cd2ab745d9f6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3AsHQAGiI",
    "aws_user_pools_web_client_id": "3isllm9e0ejrpvnprh134s9o7i",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rvtdzfvfdnfr5bkrfubvgf4yei.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tyrwonvmz5afxk6orzty3i2sgu",
    "aws_content_delivery_bucket": "switch-20190429040250-hostingbucket-switch",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://switch-20190429040250-hostingbucket-switch.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
