// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1828dab8-0ee4-4353-bf89-d3848accf89b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YQQda1NrZ",
    "aws_user_pools_web_client_id": "7gntpdogojv88uhocbfodt6hs5",
    "oauth": {}
};


export default awsmobile;
